spring:
  application:
    name: CustomerService

  data:
    mongodb:
      uri: mongodb+srv://rashmiprabhahiru_db_user:Hiruni2000@hotelsystemcluster.ehcsups.mongodb.net/hotelDB?retryWrites=true&w=majority
      database: hotelDB

server:
  address: 0.0.0.0
