package com.nsbm.group_04.InventoryService.Model;

import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.mongodb.core.mapping.Document;
import java.time.LocalDate;

/**
 * InventoryItem represents a single inventory record in the hotel management system.
 * This class is mapped to a MongoDB collection named "inventoryItems".
 * It stores stock details such as quantity, pricing, supplier information,
 * and automatically tracks creation and update timestamps.
 */
@Document(collection = "inventoryItems")  // Maps this class to MongoDB collection
public class InventoryItem {

    @Id
    // Unique identifier for each inventory item (Automatically generated by MongoDB)
    private String id;

    @NotBlank(message = "Item name is required")
    // Name of the inventory item (e.g., Towels, Soap, Bed Sheets)
    private String itemName;

    @NotBlank(message = "Category is required")
    // Category of the item (e.g., Linens, Toiletries, Kitchen Supplies)
    private String category;

    @NotNull(message = "Quantity is required")
    @Min(value = 0, message = "Quantity cannot be negative")
    // Current available stock quantity
    private Integer quantity;

    @NotNull(message = "Unit price is required")
    @Positive(message = "Unit price must be greater than zero")
    // Price per single unit of the item
    private Double unitPrice;

    @NotNull(message = "Reorder level is required")
    @Positive(message = "Reorder level must be greater than zero")
    // Minimum stock level before triggering reorder alert
    private Integer reorderLevel;

    // Physical storage location inside the hotel (e.g., Main Store, Floor 2 Storage)
    private String storageLocation;

    // Supplier or vendor providing the inventory item
    private String supplier;

    // Stock status (IN_STOCK, LOW_STOCK, OUT_OF_STOCK)
    // This value is automatically calculated in the Service layer
    private String status;

    @LastModifiedDate
    // Date when the item record was last updated
    private LocalDate lastUpdated;

    @CreatedDate
    // Date when the item record was initially created
    private LocalDate createdDate;


     //Default constructor required by Spring Data and MongoDB.
    public InventoryItem() {
    }


     //Parameterized constructor to initialize all fields.
    public InventoryItem(String id, String itemName, String category, Integer quantity,
                         Double unitPrice, Integer reorderLevel, String storageLocation,
                         String supplier, String status, LocalDate lastUpdated, LocalDate createdDate) {
        this.id = id;
        this.itemName = itemName;
        this.category = category;
        this.quantity = quantity;
        this.unitPrice = unitPrice;
        this.reorderLevel = reorderLevel;
        this.storageLocation = storageLocation;
        this.supplier = supplier;
        this.status = status;
        this.lastUpdated = lastUpdated;
        this.createdDate = createdDate;
    }

    // Getter and Setter Method
    // Standard getter and setter methods allow controlled access
    // to private fields (Encapsulation principle in OOP)

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getItemName() {
        return itemName;
    }

    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public Integer getQuantity() {
        return quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    public Double getUnitPrice() {
        return unitPrice;
    }

    public void setUnitPrice(Double unitPrice) {
        this.unitPrice = unitPrice;
    }

    public Integer getReorderLevel() {
        return reorderLevel;
    }

    public void setReorderLevel(Integer reorderLevel) {
        this.reorderLevel = reorderLevel;
    }

    public String getStorageLocation() {
        return storageLocation;
    }

    public void setStorageLocation(String storageLocation) {
        this.storageLocation = storageLocation;
    }

    public String getSupplier() {
        return supplier;
    }

    public void setSupplier(String supplier) {
        this.supplier = supplier;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public LocalDate getLastUpdated() {
        return lastUpdated;
    }

    public void setLastUpdated(LocalDate lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    public LocalDate getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(LocalDate createdDate) {
        this.createdDate = createdDate;
    }

    //Returns a string representation of the InventoryItem object.
    //Useful for debugging and logging.
    @Override
    public String toString() {
        return "InventoryItem{" +
                "id='" + id + '\'' +
                ", itemName='" + itemName + '\'' +
                ", category='" + category + '\'' +
                ", quantity=" + quantity +
                ", unitPrice=" + unitPrice +
                ", reorderLevel=" + reorderLevel +
                ", storageLocation='" + storageLocation + '\'' +
                ", supplier='" + supplier + '\'' +
                ", status='" + status + '\'' +
                ", lastUpdated=" + lastUpdated +
                ", createdDate=" + createdDate +
                '}';
    }
}
