spring:
  application:
    name: Payment-Service

  data:
    mongodb:
      uri: mongodb+srv://tharindapathirana27_db_user:1KGVfsHaD6I7J0b7@cluster0.zkd0ngl.mongodb.net/hotelDB?retryWrites=true&w=majority&appName=Cluster0

server:
  port: 8082

stripe:
  secret:
    key: ${sk_test_51T2Z3yGkjEsYRnAX0OhLknCaEgrfM4OfjA9ZgKoS4UXInxqbFl3tz9DavUN4C6EJxpBeifHnS4IbQiyHzdGD3NNh005N0JEYcR}
  public:
    key: pk_test_51T2Z3yGkjEsYRnAX8zIrI0m0sPSzLxbdBSOEJIKa8QHJ8sQ1RuZqbk0nJAwSBBZ93vG4kIN5NYVIQ67XWyjsQJ9d00NdIn7iQO

frontend:
  url:

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG